services:
  - type: web
    name: pastebin-service
    runtime: docker
    build:
      dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: pastebin-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: pastebin-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: pastebin-db
          property: password

databases:
  - name: pastebin-db
    plan: free
    databaseName: pastebin
    user: pastebin_user