spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pastebin}
    username: ${DB_USERNAME:pastebin_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true